### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by patrickjwright** [GEUS-Glaciology-and-Climate/GC-Net-evaluation#22]
It would be useful to have a `requirements.txt` for the required package versions necessary to run the code in this repo.

**Comment by BaptisteVandecrux** [comment]
Just created a requirement file automatically (https://github.com/GEUS-Glaciology-and-Climate/GC-Net-evaluation/commit/8e0c67158d7558991ac3bd9c867de92a95488127).

But not sure how you plan to use it.
For example pynead needs to be installed from github, some of the jaws and metpy functions are not used anymore (but could be brought back in use at some point).

**Comment by patrickjwright** [comment]
This looks great for now. Could be installed with `pip install -r /path/to/requirements.txt`.

This just saves some time/headache of having to run the program and follow tracebacks due to unmet dependencies to figure out what is needed, and install things one by one.

Anything that needs a custom install (like `pynead`) should be noted in the ReadMe.
