### ISSUE TITLE
file path does not match repo name

### ISSUE THREAD

**Issue by patrickjwright** [GEUS-Glaciology-and-Climate/GC-Net-evaluation#23]
Trying to run `3_GC-Net_L1_climatologies.py`, I get the following error:

```
FileNotFoundError: [Errno 2] No such file or directory: '../GC-Net-Level-1-data-processing/metadata/GC-Net_location.csv'
```
The cloned repo is: `GC-Net-level-1-data-processing` (lower-case `l` in `level`)

**Comment by BaptisteVandecrux** [comment]
yes please correct this,
I don't know why my local copy of GC-Net-level-1-data-processing is misnamed.
